export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const SELECT_ELEMENT = 'SELECT_ELEMENT';
export const DESELECT_ELEMENT = 'DESELECT_ELEMENT';