export const FETCH_THREADS_REQUEST = 'FETCH_THREADS_REQUEST';
export const FETCH_THREADS_SUCCESS = 'FETCH_THREADS_SUCCESS';
export const FETCH_THREADS_FAILURE = 'FETCH_THREADS_FAILURE';



//  module.exports = {FETCH_THREADS_REQUEST,FETCH_THREADS_SUCCESS,FETCH_THREADS_FAILURE}